version: '3.8'

services:
    app:
        image: 'pension'
        build: ./
        ports:
            -   "8081:8081"
        depends_on:
            -   postgresqldb
    postgresqldb:
        image: postgres:latest
        ports:
            -   "5432:5432"
        environment:
            - POSTGRES_USER=isa_user
            - POSTGRES_PASSWORD=isa_password
            - POSTGRES_DB = test_one